version: '3'
services:
  mongo:
    image: mongo:4.0.6
    container_name: mongo-node
  redis:
    image: redis:5.0.3
    container_name: redis-node
  watcher:
    build: .
    image: watcher
    container_name: watcher-node
    depends_on:
      - mongo
      - redis
